# Generated by Django 4.1.4 on 2023-07-21 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticationApp', '0007_remove_userprofile_hoobie_delete_hobbies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QRCode',
            new_name='QrCodeModel',
        ),
    ]
