# Generated by Django 4.1.4 on 2023-07-21 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticationApp', '0008_rename_qrcode_qrcodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
